export const lightTheme = {
  bg: '#ffffff',
  fg: '#000000',
  primaryButtonBgColor: '#fd3a3a',
  primaryButtonTextColor: '#ffffff',
  searchBarBg: '#e9e9e9',
  textColor: '#000000',
  placeholderColor: '#888888',
  modalBg: '#ffffff',
  modalTitleColor: '#333333',
  modalBodyColor: '#555555',
  closeButtonBg: '#fd3a3a',
  closeButtonText: '#ffffff',
  closeButtonHover: '#dd3232',
  confirmButtonBg: '#28a745',
  confirmButtonText: '#ffffff',
  confirmButtonHover: '#218838',
  pageIndicatorColor: '#fd3a3a',
  pageIndicatorActiveColor: '#ffffff',
  pageIndicatorBg: '#ffffff',
  pageIndicatorActiveBg: '#fd3a3a',
  changePageButtonBg: '#ffffff',
  changePageButtonText: '#000000',
}

export const darkTheme = {
  bg: '#000000',
  fg: '#ffffff',
  primaryButtonBgColor: '#fd3a3a',
  primaryButtonTextColor: '#ffffff',
  searchBarBg: '#333333',
  textColor: '#ffffff',
  placeholderColor: '#888888',
  modalBg: '#333333',
  modalTitleColor: '#ffffff',
  modalBodyColor: '#cccccc',
  closeButtonBg: '#fd3a3a',
  closeButtonText: '#ffffff',
  closeButtonHover: '#dd3232',
  confirmButtonBg: '#28a745',
  confirmButtonText: '#ffffff',
  confirmButtonHover: '#218838',
  pageIndicatorColor: '#fd3a3a',
  pageIndicatorActiveColor: '#ffffff',
  pageIndicatorBg: '#333333',
  pageIndicatorActiveBg: '#fd3a3a',
  changePageButtonBg: '#333333',
  changePageButtonText: '#ffffff',
}
